services:
  - docker

sudo: required

before_install:
  - export CACHE_DATE="$(date --utc +%Y%m%dT%H%M%SZ)"

install:
  - ./devel/pull

script:
  - ./devel/build

after_success:
  - ./devel/push-from-travis
