services:
  - docker

sudo: required

before_install:
  - export CACHE_DATE="$(date --utc +%Y%m%dT%H%M%SZ)"

install:
  - ./devel/pull

script:
  - ./devel/build

after_success:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" ]]; then
      echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_LOGIN --password-stdin;
      ./devel/push;
    fi
